config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  get 'home', to: 'page#home'
  get 'about', to: 'page#about'

  resources :rooms do
    resource :messages
  end

  devise_for :users
  devise_scope :user do
    get 'users', to: 'devise/session#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name

  scope :public_rooms, -> { where(is_private: :false) }

  after_create_commit { broadcast_append_to 'rooms' }

  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :all_except, -> (user) { where.not(id: user) }

  after_create_commit { broadcast_append_to 'user' }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end

  private

  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.new

    @rooms = Room.all.public_rooms
    @users = User.all.all_except(current_user)
  end

  def show
    @room = Room.new
    @message = Message.new

    @rooms = Room.all.public_rooms
    @users = User.all.all_except(current_user)

    @current_room = Room.find(params[:id])
    @messages = @current_room.messages.order(created_at: :asc)

    render 'index'
  end

  def create
    @room = Room.create(name: params[:room][:name])
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render renderig_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_flash_messages.html.erb
<section data-controller="flash-messages">
  <% if notice %>
    <div data-flash-messages-target="deleteButton" class="notification is-success is-light">
      <button data-action="click->flash-messages#removeFlashMessage"class="delete"></button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert %>
    <div data-flash-messages-target="deleteButton" class="notification is-danger">
      <button data-action="click->flash-messages#removeFlashMessage" class="delete"></button>
      <p><%= alert %></p>
    </div>
  <% end %>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <%= link_to 'Rails Chat', root_path, class: 'title' %>
    </div>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <% if current_user %>
        <%= link_to 'Start chatting', rooms_path, class: 'navbar-item' %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'button is-warning' %>
          <% else %>
            <%= link_to 'login', new_user_session_path, class: 'button is-light' %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'button is-primary' %>
          <% end %>
        </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <section class="section">
          <%= yield %>
      </section>
    </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: [@current_room, @message], remote: true, class: 'field') do |form| %>
  <div class="panel-block">
    <%= form.text_field :body, autocomplete: 'off', class: 'input mr-2' %>
    <%= form.submit 'Send', data: { disable_with: true }, class: 'button is-primary' %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class='panel-block'>
    <%= message.user.email %> ~> <%= message.body %>
</div>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/home.html.erb
<div class="card">
  <div class="card-header">
    <div class="card-header-title">
      <h2 class="subtitle is-3">How to start chatting</h2>
    </div>
  </div>

  <div class="card-content">
    <div class="content">
      <div class='columns is-mobile'>
        <div class='column is-5'>
          <div class='list'>
            <ul>
              <li class='list-item'>
                Create an account in the button that is in the navbar.
              </li>
              <li class='list-item'>
                Login in your account.
              </li>
              <li class='list-item'>
                Click in the button start chatting that is also in the navbar.
              </li>
              <li class='list-item'>
                Now happy chatting ;)
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room, remote: true, class: 'field') do |form| %>
  <div class="panel-block">
    <%= form.text_field :name, autocomplete: 'off', class: 'input mr-2' %>
    <%= form.submit data: { disable_with: false }, class: 'button is-primary' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="panel-block">
  <p class="control">
    <%= link_to room.name, room_path(room) %>
  </p>
</div>

app/views/rooms/index.html.erb
<div class="columns">
  <aside class="column is-4" data-controller="chatter-tabs">
      <div class="panel">
          <p class="panel-heading has-text-centered">Chatter</p>

          <p class="panel-tabs">
            <a data-chatter-tabs-target="usersTab" data-action="click->chatter-tabs#activateTab" class="is-active">
              Users
            </a>
            <a data-chatter-tabs-target="roomsTab" data-action="click->chatter-tabs#activateTab">
              Public Rooms
            </a>
          </p>

          <%= turbo_stream_from 'users' %>
          <div data-chatter-tabs-target="users" id="users" class="limit-height">
            <% @users.each do |user| %>
              <%= render 'users/user', user: user %>
            <% end %>
          </div>

          <%= turbo_stream_from 'rooms' %>
          <div data-chatter-tabs-target="rooms" id="rooms" class="limit-height">
            <%= render 'rooms/form', room: @room %>
            <% @rooms.each do |room| %>
              <%= render 'rooms/room', room: room %>
            <% end %>
          </div>
      </div>
  </aside>

  <% if defined?(@current_room) %>
    <div id="current_room" class="column">
      <div class="panel">
        <p class="panel-heading has-text-centered"> <%= @current_room.name %> </p>
        <%= turbo_stream_from @current_room %>
        <div id="messages" class="limit-height">
          <% @messages.each do |message| %>
            <%= render 'messages/message', message: message %>
          <% end %>
        </div>
        <%= render 'messages/form' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="panel-block">
  <p class="control">
    <%= user.email %>
  </p>
</div>